---
apiVersion: v1
kind: Template
metadata:
  name: crc-pdf-generator
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: crc-pdf-generator
  spec:
    envName: ${ENV_NAME}
    objectStore:
    - ${PDF_BUCKET}
    kafkaTopics:
    - replicas: 1
      partitions: 1
      topicName: pdf-generator.updated.report
    optionalDependencies:
    - ros-backend
    - chrome-service
    deployments:
    - name: api
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
          apiPath: crc-pdf-generator
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        env:
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: ASSETS_HOST
          value: ${ASSETS_HOST}
        - name: PROXY_AGENT
          value: ${PROXY_AGENT}
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUESTS}
            memory: ${MEMORY_REQUESTS}
parameters:
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 3000m
- description: Cpu requests of service
  name: CPU_REQUESTS
  value: 1500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 2048Mi
- description: memory limit of service
  name: MEMORY_REQUESTS
  value: 1024Mi
- name: MIN_REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/crc-pdf-generator
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "false"
- description: ClowdEnv Name
  name: ENV_NAME
  value: "crc-pdf-generator"
  required: true
- description: Logging level for the server
  name: LOG_LEVEL
  value: "debug"
- description: Dynamic name for the s3 bucket based on env
  name: PDF_BUCKET
  value: "crc-generated-pdfs"
- description: Enable large test queries
  name: QUERY_LARGE_DATASET
  value: "false"
- description: Scalprum template ASSETS host
  name: ASSETS_HOST
  value: "blank"
- description: Proxy agent
  name: PROXY_AGENT
  value: "blank"
- description: Retention time span for pdf in MS (8 hours default)
  name: ENTRY_TIMEOUT
  value: "28800000"
